{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mini",
    "module": "mini-util",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "m3uzfrvzmjdslljueiseqjnrym"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-util-1.0.jar",
          "url": "mini-util-1.0.jar",
          "size": 67171,
          "sha512": "cc685bd7367088f02eb7bb1c3b7ea501887c309efcbe8a9d6506db58d0517deeba361bbc6c6b1f1b701dfd8877c5dd1402e893738e0eba4c101ab7fcf225c194",
          "sha256": "aa22dfa3c5f68b28db241cce201e3b4241ae8dc1b67e1c754aeab0c2d347f37e",
          "sha1": "07155359af59b080bf2f76a2bfc4468332b10881",
          "md5": "a846b9b4913461e2613da5f89ab71c2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-util-1.0.jar",
          "url": "mini-util-1.0.jar",
          "size": 67171,
          "sha512": "cc685bd7367088f02eb7bb1c3b7ea501887c309efcbe8a9d6506db58d0517deeba361bbc6c6b1f1b701dfd8877c5dd1402e893738e0eba4c101ab7fcf225c194",
          "sha256": "aa22dfa3c5f68b28db241cce201e3b4241ae8dc1b67e1c754aeab0c2d347f37e",
          "sha1": "07155359af59b080bf2f76a2bfc4468332b10881",
          "md5": "a846b9b4913461e2613da5f89ab71c2d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-util-1.0-javadoc.jar",
          "url": "mini-util-1.0-javadoc.jar",
          "size": 498471,
          "sha512": "7d25d032489066ea3bfdf0588523ae9c1f146a977009f6b9b67a39d5ad2f9465ea7094f0d883271a8c0dbcb8e3ee0ce3d90fbb98e7b03db83463fd53887682e4",
          "sha256": "1d3aeeccbf6ecfef18c47c62d71dab39a75bcfe94e4d5df93d5cde295f791512",
          "sha1": "0c49b1e302a50605974b3cedc8b6a16fa0614942",
          "md5": "1e8f8a152db5c31ba65719bbfcd38406"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-util-1.0-sources.jar",
          "url": "mini-util-1.0-sources.jar",
          "size": 23877,
          "sha512": "1b56f23b20f9f43f5aeb1587a7126e9a2713003ffd50df103b9b23d24e3b87769fa43328fce68f93bc059d28e86d9aaf68377ddea45b4a3fc59c4ca71b9d37b3",
          "sha256": "506c5ac80af0c752cf65803b37d23ff66b8ef16668a4c9ae9da766481626ab07",
          "sha1": "92d9154c104be09f85680d487afb507f92839031",
          "md5": "5e13f1a002093d254a6c59d443afb457"
        }
      ]
    }
  ]
}
