{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mini",
    "module": "mini-util",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "ubuaal7utfhunddlq2ycnixh7m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha5"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.0-alpha1"
          }
        }
      ],
      "files": [
        {
          "name": "mini-util-1.0.jar",
          "url": "mini-util-1.0.jar",
          "size": 67151,
          "sha512": "01f939131a8691456d57cd21c3bd2c7c69b256ede7bb0146323389567bb6324304d1b900d149a96ffa42c6e7e53271f216b7f6885250e3276ca35ac147c259df",
          "sha256": "f5e623f3baf513b232670ff6a129a58b5be4ed674c22a273379562090bc9558b",
          "sha1": "619a2fed7df06b51fbfe46550ef7e1f5f9fa163f",
          "md5": "3f84783b36445244f72619eabf4b4041"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha5"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.0-alpha1"
          }
        }
      ],
      "files": [
        {
          "name": "mini-util-1.0.jar",
          "url": "mini-util-1.0.jar",
          "size": 67151,
          "sha512": "01f939131a8691456d57cd21c3bd2c7c69b256ede7bb0146323389567bb6324304d1b900d149a96ffa42c6e7e53271f216b7f6885250e3276ca35ac147c259df",
          "sha256": "f5e623f3baf513b232670ff6a129a58b5be4ed674c22a273379562090bc9558b",
          "sha1": "619a2fed7df06b51fbfe46550ef7e1f5f9fa163f",
          "md5": "3f84783b36445244f72619eabf4b4041"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-util-1.0-javadoc.jar",
          "url": "mini-util-1.0-javadoc.jar",
          "size": 498511,
          "sha512": "690a97cbfb9812b8361b2f6df6ccb52538fa8f430769df4119a7efc17a5b8d167bebd4f16a99fe7ff0f737c13cee333b0e8c80c0f880536fd85f3e5156f5c877",
          "sha256": "b039da2e08e995667746a3363ba856f5dc99542183e638ee46825ca587ad3e1e",
          "sha1": "5b9b6e0293c84c796951f3dae552640cc65b6dbe",
          "md5": "819c746d30f8526b767624f17f6c902a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-util-1.0-sources.jar",
          "url": "mini-util-1.0-sources.jar",
          "size": 23861,
          "sha512": "caccad49008702d411393d560ce3d9e3cee3f1b7c72c0cea9b1f82311c67695f989186a8473a817560b4a0906540753aa3646fc1749b8358f6211350e7c26ca9",
          "sha256": "f3ab46f79bf0d1c64fabcdefe106578ce6d24b0b8fa58448b6f9dae930e32133",
          "sha1": "8e653affcc007dc4d7d508d0d00223bc7298ce11",
          "md5": "a292c489a60a128f3a70d1a3e99ed1f8"
        }
      ]
    }
  ]
}
