{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mini",
    "module": "mini-util",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t5pxcdkkzvcw3ig6djo42tbvqm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-util-1.0.jar",
          "url": "mini-util-1.0.jar",
          "size": 67086,
          "sha512": "ee2d82804e279d985eb9cc60727ffd4fe1082fcec3583eecfe83b06e54268b771ad86f8f867d60d03a3d71b21f7a5d189c85edeafe165ea6d07657ed4c9ba39c",
          "sha256": "aefab04afc58b6578975d569cb747734001fa74f2b083460897fb0eb520e97a9",
          "sha1": "79a00c4434c9c5ddca4491b1cdeb630bb2d57481",
          "md5": "93750c5b9dbc17f851ed3853492682fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-util-1.0.jar",
          "url": "mini-util-1.0.jar",
          "size": 67086,
          "sha512": "ee2d82804e279d985eb9cc60727ffd4fe1082fcec3583eecfe83b06e54268b771ad86f8f867d60d03a3d71b21f7a5d189c85edeafe165ea6d07657ed4c9ba39c",
          "sha256": "aefab04afc58b6578975d569cb747734001fa74f2b083460897fb0eb520e97a9",
          "sha1": "79a00c4434c9c5ddca4491b1cdeb630bb2d57481",
          "md5": "93750c5b9dbc17f851ed3853492682fb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-util-1.0-javadoc.jar",
          "url": "mini-util-1.0-javadoc.jar",
          "size": 498419,
          "sha512": "32ea632f5fa2798164ba13f1d6036bb25d87a91c28bf262c54b2638e5a59fef9d6b61635bdb893783187e0cd6c0b1ca52a0dd67bce76e7342bcce0b85772ae25",
          "sha256": "fe8cf699df0edf00828fa0108bb6e569f79b8e072978840fed465e3cbd0b3224",
          "sha1": "aeb3b931090c613c8958f3780142f33e48848dd5",
          "md5": "714daa8a74870d45c2dafc22e2aed523"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-util-1.0-sources.jar",
          "url": "mini-util-1.0-sources.jar",
          "size": 23861,
          "sha512": "01aecd30d812575353cda0511bbfe6d22c83d56273eb63460bef4f83a83f12bbaf6ca368c32972036bfba9041e04f529b101e09a7c4612431397fece36f06149",
          "sha256": "ae790c4843f91de88b52d6d07ba32458dd807538c6fbd100654a6e34f0940164",
          "sha1": "711b8b3b9cccd228aa88f684dd87973e4cfe5130",
          "md5": "01ad4cc6e53ee21ced5cb319541f989c"
        }
      ]
    }
  ]
}
