{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mini",
    "module": "mini-core",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "vjjmndzjrzfyvnmo76k6jouq5y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.inject.extensions",
          "module": "guice-multibindings",
          "version": {
            "requires": "4.2.3"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0-rc6"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha5"
          }
        },
        {
          "group": "javax.transaction",
          "module": "transaction-api",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.0-alpha1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.3"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "aopalliance",
          "module": "aopalliance",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.47"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "7.1"
          }
        }
      ],
      "files": [
        {
          "name": "mini-core-1.0.jar",
          "url": "mini-core-1.0.jar",
          "size": 374951,
          "sha512": "0146d2efa7416b089f442f335de7476712db755486b25bf53402b726cbec5d30bba7d51d51cc6622e5d78ebb7bf3b476f3c58b481aab4d59de63e5a886f7dcd1",
          "sha256": "cc2fa9f5017a3da48a17b69407cb0ca90bc5a598b32afd5fb95b72062eca3fcb",
          "sha1": "9fad2225d9131eafbc583517ddda049a907e09f8",
          "md5": "25ec5cf1bdff57f27f45b4f89d01dfe9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "com.google.inject.extensions",
          "module": "guice-multibindings",
          "version": {
            "requires": "4.2.3"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0-rc6"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha5"
          }
        },
        {
          "group": "javax.transaction",
          "module": "transaction-api",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.0-alpha1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.3"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "aopalliance",
          "module": "aopalliance",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.47"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "7.1"
          }
        }
      ],
      "files": [
        {
          "name": "mini-core-1.0.jar",
          "url": "mini-core-1.0.jar",
          "size": 374951,
          "sha512": "0146d2efa7416b089f442f335de7476712db755486b25bf53402b726cbec5d30bba7d51d51cc6622e5d78ebb7bf3b476f3c58b481aab4d59de63e5a886f7dcd1",
          "sha256": "cc2fa9f5017a3da48a17b69407cb0ca90bc5a598b32afd5fb95b72062eca3fcb",
          "sha1": "9fad2225d9131eafbc583517ddda049a907e09f8",
          "md5": "25ec5cf1bdff57f27f45b4f89d01dfe9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-core-1.0-javadoc.jar",
          "url": "mini-core-1.0-javadoc.jar",
          "size": 1345696,
          "sha512": "cee02379a02bf36acc1b3d64f41d47571c397b67f43b4313dc7aac7b12fed3674836fe8b3da2628572d941dcf53c40d24814a8a2809690b713b431257e520f9b",
          "sha256": "f19a5cece0ad8fdbf0bc9edd6555dc665023fd0c6e24a44bac96639e6171e77b",
          "sha1": "8c0984308c92239fecc33f263d45be4630b92e58",
          "md5": "c6e871dc2fd18f5840c721565b949011"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-core-1.0-sources.jar",
          "url": "mini-core-1.0-sources.jar",
          "size": 195822,
          "sha512": "c3cddfc582450a159864c87ee054c72c49da99211c9805f5d0a04a365c2f1cd1ce446b649a3b3a769f6e9f79448caf5780a3ff88aa3b4ea5702414a32b1c8cfc",
          "sha256": "f0c51b94726ce5e2f6d6f1ade14b33238e34aaf36cda4f91cd0ae5f7081b4fb4",
          "sha1": "9b20486d5f46f5700ad69453608c970775f6b1b6",
          "md5": "082e467321b7d4f6c775ad6f8f7c7dc1"
        }
      ]
    }
  ]
}
