{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mini",
    "module": "mini-mvc",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "wrr7usmcpjh7fpn3t7lhwzcule"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.3.4.RELEASE"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "6.1.5.Final"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.0-alpha1"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-util",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-mvc-1.0.jar",
          "url": "mini-mvc-1.0.jar",
          "size": 35802,
          "sha512": "c8b678d829e91d06d23614caac4cda6e345964a93d1a456e91e58b1feec34d8b83361005258195e97cd0f7c1f2cfd4c3a937e4672ef2e773db3a494c2bd75b93",
          "sha256": "2a36f6ef431790f9a67d2305cd25fd99592df3f6f0ad30830eb91b14b7c7fd30",
          "sha1": "6e59acaafa3988dfd8c4560ff90a4785c9158e3b",
          "md5": "485afb0a2792e99ae2a584071e33cd7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.3.4.RELEASE"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "6.1.5.Final"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.0-alpha1"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-util",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-mvc-1.0.jar",
          "url": "mini-mvc-1.0.jar",
          "size": 35802,
          "sha512": "c8b678d829e91d06d23614caac4cda6e345964a93d1a456e91e58b1feec34d8b83361005258195e97cd0f7c1f2cfd4c3a937e4672ef2e773db3a494c2bd75b93",
          "sha256": "2a36f6ef431790f9a67d2305cd25fd99592df3f6f0ad30830eb91b14b7c7fd30",
          "sha1": "6e59acaafa3988dfd8c4560ff90a4785c9158e3b",
          "md5": "485afb0a2792e99ae2a584071e33cd7c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-mvc-1.0-javadoc.jar",
          "url": "mini-mvc-1.0-javadoc.jar",
          "size": 498050,
          "sha512": "522da8132742f3fcc6100535b0eaea8d0c3cfcb8beab61ba7b737591e057961b7c280da0f017a811c0641c88b064fa42381b4a4b771883e951fb5b88dd4bbceb",
          "sha256": "cd74944a0e46297b7871c7b2c34aea6840d9ffc00cb70d4daa8faf186cae922a",
          "sha1": "63a6791b399be46b9b6458801922aba4f43e66fc",
          "md5": "fad063627acc5ef3953acf998556227e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-mvc-1.0-sources.jar",
          "url": "mini-mvc-1.0-sources.jar",
          "size": 20387,
          "sha512": "10ff7dbe89d95283886af0782f67e9e597ad867ea2ad8f399448d8360e0ed07489a9452a3e6a12ac3c055e380baddaddaf9eab17f9f88f5c5cabed7d9ecd6f32",
          "sha256": "90d0ff8e5cdb2baf134790511419a8b3dc16ac5934ed318102d461b3f4a363b1",
          "sha1": "34b79f781c7dd59f88c1aaaa7babbb60b3855982",
          "md5": "af78994c9c31ab179d48d52785cfaddd"
        }
      ]
    }
  ]
}
