{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mini",
    "module": "mini-mvc",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "v7wbv7l3nrhj7f6wizfsbqdpoq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.3.4.RELEASE"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "6.1.5.Final"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.0-alpha1"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-util",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-mvc-1.0.jar",
          "url": "mini-mvc-1.0.jar",
          "size": 36929,
          "sha512": "1ab5d8cec9b91f3e719f0ae3fa03898e89874eaccd4125e15c3eed6ff944ba2f80ece7163af39804ffccab1ad1411577af17e955d1f26b9f9853b1b377bc8295",
          "sha256": "a3ef0db1552ea881d857f9255532d898c19275632c1743d687800d16b90738f9",
          "sha1": "b3720c3cd7a4a02705aa1fa0f060a00808df417b",
          "md5": "ff6a3c413371f21e3fc9c960762770df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.3.4.RELEASE"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "6.1.5.Final"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.0-alpha1"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-util",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-mvc-1.0.jar",
          "url": "mini-mvc-1.0.jar",
          "size": 36929,
          "sha512": "1ab5d8cec9b91f3e719f0ae3fa03898e89874eaccd4125e15c3eed6ff944ba2f80ece7163af39804ffccab1ad1411577af17e955d1f26b9f9853b1b377bc8295",
          "sha256": "a3ef0db1552ea881d857f9255532d898c19275632c1743d687800d16b90738f9",
          "sha1": "b3720c3cd7a4a02705aa1fa0f060a00808df417b",
          "md5": "ff6a3c413371f21e3fc9c960762770df"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-mvc-1.0-javadoc.jar",
          "url": "mini-mvc-1.0-javadoc.jar",
          "size": 497090,
          "sha512": "50452aa16c58efb4715678a578767281ec82cdeb7da7ba2b2689ecc4835a275342ade4d22bcf8f2c1262084f4d5a9c070fa886f5d277784f30527916f6d9db33",
          "sha256": "2d41d01f25c84694e2430d1da766d92209ce97903f70acbaf157b91f7c621542",
          "sha1": "6d4076c5b80ca1fb8f87f87856b8d14e496367b8",
          "md5": "bb3b90f92bebb0927771a1507ba1eb04"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-mvc-1.0-sources.jar",
          "url": "mini-mvc-1.0-sources.jar",
          "size": 20679,
          "sha512": "abd0a208f135af658a3e6031665b545a30ebc712b40856e577be4b468b7fc767d397b4d6f3c1c51498c6f7ff226aecf2ab6e4803b4e09d27c6df97daf99f4f28",
          "sha256": "8c2cda134da48866d5038c850e39e5520667260ca2cc15e30ae8fdb28f09ba44",
          "sha1": "eb3283152d3f978e84abe6896f032a698e241e7e",
          "md5": "b8da477c5133e17050aed9086cb01dff"
        }
      ]
    }
  ]
}
