{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mini",
    "module": "mini-mvc",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "sbocpanepzbanibmplcsvkwwbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.3.5.RELEASE"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.5.RELEASE"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "6.1.6.Final"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.2.10.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.2.10.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.2.10.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.2.10.RELEASE"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.0-alpha1"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-util",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-mvc-1.0.jar",
          "url": "mini-mvc-1.0.jar",
          "size": 36866,
          "sha512": "4800b25c955879d12d1d5cb07686c8d190cf61d3c2a000ac54ea007ffa31808f364617c1f376106f80bc2cf3d9ec053bb2d614f6cac780516fb2dc1dfaf9d42f",
          "sha256": "10cf385323c7e79287d195f42b0571bc2c6d20b0a2bf1c983175644f7ea0c308",
          "sha1": "11dcbce16fbfa810cafed18d71fe9f29918b8d44",
          "md5": "abc47851c5472e6197118fe14b10d332"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.3.5.RELEASE"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.5.RELEASE"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "6.1.6.Final"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.2.10.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.2.10.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.2.10.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.2.10.RELEASE"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.0-alpha1"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-util",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-mvc-1.0.jar",
          "url": "mini-mvc-1.0.jar",
          "size": 36866,
          "sha512": "4800b25c955879d12d1d5cb07686c8d190cf61d3c2a000ac54ea007ffa31808f364617c1f376106f80bc2cf3d9ec053bb2d614f6cac780516fb2dc1dfaf9d42f",
          "sha256": "10cf385323c7e79287d195f42b0571bc2c6d20b0a2bf1c983175644f7ea0c308",
          "sha1": "11dcbce16fbfa810cafed18d71fe9f29918b8d44",
          "md5": "abc47851c5472e6197118fe14b10d332"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-mvc-1.0-javadoc.jar",
          "url": "mini-mvc-1.0-javadoc.jar",
          "size": 503774,
          "sha512": "183727e6b63ac052498d279d2e77c6a24bb180ba2b884d2d644591216112c30fb3832741278edb8e739a7c732645b1cca47328c7846e7eeefaad460c36e20ce7",
          "sha256": "500e6c34a9d561817d0a77b89eeb06d070ed1f18bf64ebb6bb290d4c971691a9",
          "sha1": "7fe4dcb64fa92a77548daaf28a4a44f55d3b4ee6",
          "md5": "d4e6862d688657c65f75305cca4288e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-mvc-1.0-sources.jar",
          "url": "mini-mvc-1.0-sources.jar",
          "size": 21541,
          "sha512": "100ca5d152333a4cdb6764eec12f08aefe83b08e19fc6f480b76d65d39eba05d93e23865a64580f34cd220eec8b974df5f62549fc480ece3e031876ba4374826",
          "sha256": "2319b2074d2b6103efcea3e5fda9ae03c43428c080e083906ed98159462895fd",
          "sha1": "5edbc61996c73d1cdd1a5decd10b63ffe0815a89",
          "md5": "a4ecfc902e2dbf537b656d6305db6470"
        }
      ]
    }
  ]
}
