{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mini",
    "module": "mini-jdbc",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "op4a3uahyja53ozpweba4klopy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.data",
          "module": "spring-data-jdbc",
          "version": {
            "requires": "2.0.5.RELEASE"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-data",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-jdbc-1.0.jar",
          "url": "mini-jdbc-1.0.jar",
          "size": 16137,
          "sha512": "21e67d992d81010020c7b9dda16591570d607b423b30b005309716a0441e7c4ee0606d45db46b4c725e34a84927b1eb5d97e3eb46a7ecf25fc24d2e103e9f80b",
          "sha256": "dcaab2e42e820adbcdb683548325838f02bd60674cc21df0a28ecd92a6beb8fe",
          "sha1": "2a4aa5a9be17da989b186ac2f4aa9b174e21c194",
          "md5": "f0c9bd70775360ff15dcc4e7907dfabf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jdbc",
          "version": {
            "requires": "2.0.5.RELEASE"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-data",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-jdbc-1.0.jar",
          "url": "mini-jdbc-1.0.jar",
          "size": 16137,
          "sha512": "21e67d992d81010020c7b9dda16591570d607b423b30b005309716a0441e7c4ee0606d45db46b4c725e34a84927b1eb5d97e3eb46a7ecf25fc24d2e103e9f80b",
          "sha256": "dcaab2e42e820adbcdb683548325838f02bd60674cc21df0a28ecd92a6beb8fe",
          "sha1": "2a4aa5a9be17da989b186ac2f4aa9b174e21c194",
          "md5": "f0c9bd70775360ff15dcc4e7907dfabf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-jdbc-1.0-javadoc.jar",
          "url": "mini-jdbc-1.0-javadoc.jar",
          "size": 436212,
          "sha512": "33477c046726d9bd77d2ebad6d5edfe33b1d802e93f4002e0a17bfe411e801887ca4d951dd53d8184f10fe3a3becc6370e70db489d405e0df2ce6841520144f3",
          "sha256": "5b48fe74ddf444f4fe939817b445bfed6612d63bc898de770e496fdb0769cb4e",
          "sha1": "084d2b067070aecc5318278181d41af2f41c569b",
          "md5": "6194a22750b3086ac1582297ff50e915"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-jdbc-1.0-sources.jar",
          "url": "mini-jdbc-1.0-sources.jar",
          "size": 8122,
          "sha512": "75254397bf2592ae80a50a36da10dde9b813a86764471378d4f1abdd1da72c9ae3e8790083d6e4f04da4803df93fccaf0e4cd5aa10bcdea6a0492a9c71926ec5",
          "sha256": "2b8783440322fce9af3abaaa95871d746568bb6307e3985de70672158d4f644e",
          "sha1": "9e70e0c43910b2daf01b15db82514c87798e395c",
          "md5": "b792e5d50854321fa092ef68cf09e99f"
        }
      ]
    }
  ]
}
