{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mini",
    "module": "mini-jdbc",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "exqcf37hdneufljkqv3qxfphpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.data",
          "module": "spring-data-jdbc",
          "version": {
            "requires": "2.0.5.RELEASE"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-data",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-jdbc-1.0.jar",
          "url": "mini-jdbc-1.0.jar",
          "size": 16141,
          "sha512": "8a01c2e77f0d4839e690f5179dd5bd8020d6cb84f4af7236da538f347ccb2c2c38f1a19c9c7a79e9a5c7a132cfa1c95034718db555cf10519fa80a738cf80deb",
          "sha256": "5a9963e7a21e68df4d658760508d21c41cc1029cf27e1d166c75d1e5ed6bb379",
          "sha1": "6aea78c2f6bd9771a57156aef51ed221047bf6b2",
          "md5": "59102e922c34b6d6d9d93111ecc12c7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jdbc",
          "version": {
            "requires": "2.0.5.RELEASE"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-data",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-jdbc-1.0.jar",
          "url": "mini-jdbc-1.0.jar",
          "size": 16141,
          "sha512": "8a01c2e77f0d4839e690f5179dd5bd8020d6cb84f4af7236da538f347ccb2c2c38f1a19c9c7a79e9a5c7a132cfa1c95034718db555cf10519fa80a738cf80deb",
          "sha256": "5a9963e7a21e68df4d658760508d21c41cc1029cf27e1d166c75d1e5ed6bb379",
          "sha1": "6aea78c2f6bd9771a57156aef51ed221047bf6b2",
          "md5": "59102e922c34b6d6d9d93111ecc12c7f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-jdbc-1.0-javadoc.jar",
          "url": "mini-jdbc-1.0-javadoc.jar",
          "size": 436167,
          "sha512": "89b76050d2ab6243f7eae23a71c410702d57afbfb17532ef7a70fb6976b73dcc09cd3a454c6ed115b5c571651af380c46bebbcb646b5981896c56dcee226eeed",
          "sha256": "16ede5efbff73dbe13b64ac1e1bc2335dcf633fe77cac8d6212bde1962a56775",
          "sha1": "ec814bb25fd819e9357e44c63bd63bec24de982b",
          "md5": "49bb489950acf0d3ce6439d2726b41df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-jdbc-1.0-sources.jar",
          "url": "mini-jdbc-1.0-sources.jar",
          "size": 8001,
          "sha512": "8ea4633e345783a383a4d3205656a46ab9601f6649877d67f4e5df6d3a5452ef8e7595fe97d4893d2a4e315bf4d1d806e2dd294dd756d0506f89d9364e4e0ad9",
          "sha256": "0cb266fc5de4291e8d8337e4a69032276ac4d72bf725c58d32b4afc861872bfa",
          "sha1": "b527766bf05287ae042525573b9027552b183280",
          "md5": "ab64738950bbbda545ead51dee5550eb"
        }
      ]
    }
  ]
}
