{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mini",
    "module": "mini-jdbc",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "5eoj53vlhzdi7e4wyla6763ygy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.data",
          "module": "spring-data-relational",
          "version": {
            "requires": "2.0.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-util",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-jdbc-1.0.jar",
          "url": "mini-jdbc-1.0.jar",
          "size": 138348,
          "sha512": "cb8201440bbf580c073990abf25d5a3d75042df6703d5541fe15c940560b5d6a439daed2f499e52ad8acf86022fdcfce03d37ac613277d4e32492f406005482d",
          "sha256": "52ffbd925d2ce335134f3bf2fdab318275594732540d3c96eb43580defb61cf9",
          "sha1": "f2aa8bffe8fb75a5ec01690f7b3bed2cc1aa57a6",
          "md5": "d46af9dffaa4fb241609e82f32bab711"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-relational",
          "version": {
            "requires": "2.0.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-util",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-jdbc-1.0.jar",
          "url": "mini-jdbc-1.0.jar",
          "size": 138348,
          "sha512": "cb8201440bbf580c073990abf25d5a3d75042df6703d5541fe15c940560b5d6a439daed2f499e52ad8acf86022fdcfce03d37ac613277d4e32492f406005482d",
          "sha256": "52ffbd925d2ce335134f3bf2fdab318275594732540d3c96eb43580defb61cf9",
          "sha1": "f2aa8bffe8fb75a5ec01690f7b3bed2cc1aa57a6",
          "md5": "d46af9dffaa4fb241609e82f32bab711"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-jdbc-1.0-javadoc.jar",
          "url": "mini-jdbc-1.0-javadoc.jar",
          "size": 663857,
          "sha512": "20b8c016a5680b880b10796c6120d3c8933b1e0ea8b9dec2f54fcf612989aa4bdf69f06cf0d1984e8c86eda5177e210a31f54c7d31758fe51c260525f6b77d6b",
          "sha256": "b6cf66772c285ccf805c0bd8ed30a1db42873fdcf71191fb983c1b245eac3788",
          "sha1": "04d6fe772d9399395d92ff4ed55f4d80d9c30f32",
          "md5": "7fbe85f3b7f24bfaa46ce61a12d35e44"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-jdbc-1.0-sources.jar",
          "url": "mini-jdbc-1.0-sources.jar",
          "size": 37837,
          "sha512": "a4abe2e9d8042abb837f0f622fad03accc7aa2ec599af89a8d66b3bcee42db18985c9421c4946971d8252981c79773278de5062e3547cfe926ee7ade266f239c",
          "sha256": "2f1d38d414da1db674f4ea06fc5f8dcf9361020cc65e95b97c6ba9af9f0e3208",
          "sha1": "9c80b5b7a3f368d30be1d8e0f083b6525854915c",
          "md5": "cef317c47ce3b97228542c5591e878c0"
        }
      ]
    }
  ]
}
