{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mini",
    "module": "mini-jpa",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "6qacun4byjekxemxkxihoim6me"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.4.21.Final"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-data",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-jpa-1.0.jar",
          "url": "mini-jpa-1.0.jar",
          "size": 3325,
          "sha512": "b9009bf93d01189efd0f7fbb2126a28fe8b8acb2ca301148bb44fcc9d4d859d4a7e064827e7a828f1217958f9e9bcb8baf242f62f9a4eb655c6ca8dec709878e",
          "sha256": "9999202d6c7ceaa8c9d9bf36778fb49fe6b787c736ceb19ce970fa62d288f2d8",
          "sha1": "8c54296cfa715042b731acc2bbe0903895d9096c",
          "md5": "166cbabcc61cdf1bf93dd44a36ed760f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.4.21.Final"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-data",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-jpa-1.0.jar",
          "url": "mini-jpa-1.0.jar",
          "size": 3325,
          "sha512": "b9009bf93d01189efd0f7fbb2126a28fe8b8acb2ca301148bb44fcc9d4d859d4a7e064827e7a828f1217958f9e9bcb8baf242f62f9a4eb655c6ca8dec709878e",
          "sha256": "9999202d6c7ceaa8c9d9bf36778fb49fe6b787c736ceb19ce970fa62d288f2d8",
          "sha1": "8c54296cfa715042b731acc2bbe0903895d9096c",
          "md5": "166cbabcc61cdf1bf93dd44a36ed760f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-jpa-1.0-javadoc.jar",
          "url": "mini-jpa-1.0-javadoc.jar",
          "size": 404723,
          "sha512": "25695d0f790c28188a8d6d8ef79c7835a7377b4f1a25bfb2258218c6ffc3eabb63aa8226c52056901eba517e94fb22a2607917483378c1775894aae8335e62c1",
          "sha256": "e0b32dce46dad3f56b59b3f8d2c86b0c76acffd9ca424f6ac2e553887caf8322",
          "sha1": "25864526f8147cd5337ffead0a3ce6bda98e9c62",
          "md5": "21a2c708e0513a48b40c13ada1aadbaf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-jpa-1.0-sources.jar",
          "url": "mini-jpa-1.0-sources.jar",
          "size": 2256,
          "sha512": "144600c15e3434bfbff521341c238c90dd4d8ef4dc401bb432d7807c8c85bcb29328229d3f61999c7c940304b56f446c78f7c7b870728a914a12c41dc35b4671",
          "sha256": "659794f24b3f5c1ba2708cd0f221ad01a186c6f80240b510edfd1af350ae998b",
          "sha1": "8f46c688717de0af26f8ece1f358dfedb92fe6c8",
          "md5": "446bccb12a33ab933789424d64e30bd9"
        }
      ]
    }
  ]
}
