{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mini",
    "module": "mini-jpa",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "xjb4ve6sqnh3pj2lbtft3acsmi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.3.5.RELEASE"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.4.21.Final"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-data",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-jpa-1.0.jar",
          "url": "mini-jpa-1.0.jar",
          "size": 2519,
          "sha512": "262e200ac2a6862f2623fa446d13bdc60e63086cd135dcecc8f25ba6d86e98796917f5c94de8cfc7d2ad4944a0a4df3d081bfa787f975079e01dadc17e1ec6c8",
          "sha256": "55a163dc4330288e0dc214b5af09a0d98c176ac248d3007078ef3ce47929e85b",
          "sha1": "37436fdf8ab9d6e69d32a7bbebc79011bc893ca0",
          "md5": "60cd249c9aab45c02a9289a5587678d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.3.5.RELEASE"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.4.21.Final"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-data",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-jpa-1.0.jar",
          "url": "mini-jpa-1.0.jar",
          "size": 2519,
          "sha512": "262e200ac2a6862f2623fa446d13bdc60e63086cd135dcecc8f25ba6d86e98796917f5c94de8cfc7d2ad4944a0a4df3d081bfa787f975079e01dadc17e1ec6c8",
          "sha256": "55a163dc4330288e0dc214b5af09a0d98c176ac248d3007078ef3ce47929e85b",
          "sha1": "37436fdf8ab9d6e69d32a7bbebc79011bc893ca0",
          "md5": "60cd249c9aab45c02a9289a5587678d7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-jpa-1.0-javadoc.jar",
          "url": "mini-jpa-1.0-javadoc.jar",
          "size": 403167,
          "sha512": "066c1b59e70c15df79b05fd45ec9acc92c43fb61cfde838027ad1373a073f7ce7006fd71987dfc28f5bec1b73e919d47e083ebbcda2910e53ab9097bf5a89999",
          "sha256": "2d61c1ba3d53574129e0055745c3a5a16ad87e99dda5a74cf542e9e4b2cdc3d8",
          "sha1": "c475ace1923c1b14c9087de93ceae5b8830839d7",
          "md5": "2af4b32c75466fc1505621f424f926e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-jpa-1.0-sources.jar",
          "url": "mini-jpa-1.0-sources.jar",
          "size": 1815,
          "sha512": "e1551169411cad7a544397aaaedf1778d042367776ed6022f228af6b894fe218e210d5d03ac4149bb063242c3d4c712e3d0d7ecedc2654e16af62ffc7e372508",
          "sha256": "6423ac6c71e4ff1d5819d2f7b969db23163e1ef2ff96d07db02dc905180f9644",
          "sha1": "1f9ccdd28b80e50d31707bcdc8a930e140faf6fc",
          "md5": "e5481b9a8cee61ade0c4d377def408fb"
        }
      ]
    }
  ]
}
