{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mini",
    "module": "mini-data",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "zwr7652xszexjgpr62y2ekph5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.data",
          "module": "spring-data-relational",
          "version": {
            "requires": "2.0.5.RELEASE"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "2.3.5.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.2.10.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.2.10.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.2.10.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.2.10.RELEASE"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-util",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-data-1.0.jar",
          "url": "mini-data-1.0.jar",
          "size": 94002,
          "sha512": "e498cef7ac6048e8943de595e5d198cd12b2b8c7b7a30c65b873b8df2496529d39b78b1c0c8a5cb134367d59cce83dd61abad49df354114fc9018870c121741d",
          "sha256": "8b5c8e6e65b511057b5682fdba83649d928a0761984109eee41a28cd5c621eda",
          "sha1": "4bdceb374484cc3982bc50b932925d5100910891",
          "md5": "ff0091902195a55388cc5ee9cca5d202"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-relational",
          "version": {
            "requires": "2.0.5.RELEASE"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "2.3.5.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.2.10.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.2.10.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.2.10.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.2.10.RELEASE"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-util",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-data-1.0.jar",
          "url": "mini-data-1.0.jar",
          "size": 94002,
          "sha512": "e498cef7ac6048e8943de595e5d198cd12b2b8c7b7a30c65b873b8df2496529d39b78b1c0c8a5cb134367d59cce83dd61abad49df354114fc9018870c121741d",
          "sha256": "8b5c8e6e65b511057b5682fdba83649d928a0761984109eee41a28cd5c621eda",
          "sha1": "4bdceb374484cc3982bc50b932925d5100910891",
          "md5": "ff0091902195a55388cc5ee9cca5d202"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-data-1.0-javadoc.jar",
          "url": "mini-data-1.0-javadoc.jar",
          "size": 626218,
          "sha512": "ae49f74092ebada0eabbf4796787fcefe8e22a4a55a16430d0b6d01bef20aa1ae6a94639917f55b184085316c01f2a5de832599c49ff78b01f04f0918559688a",
          "sha256": "8bd05e4e464bf758d5f06edf8ae63227dc7d59fd65b669aad4f3793f9e95440c",
          "sha1": "2c4f9453d6da6bffa8a6dffd5523ddee0851d55c",
          "md5": "0170f8d6b0d58ce85b7888d4b94b6e97"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-data-1.0-sources.jar",
          "url": "mini-data-1.0-sources.jar",
          "size": 31188,
          "sha512": "3242e0a4609ded663ffefe7c69ffbf9ad568d3e286b586d017b6ed597e563d56f686c34376e213f7c8acf188b0dcb445c5e5ed27f80756c96af47b569844e3dd",
          "sha256": "a4628b033cc142d7dbb7e51de125582d3435182ca02139441419a162e4c51b06",
          "sha1": "eafb3f0f2072b5a00426cd93cd1c91d4b1ba7ef7",
          "md5": "5a899190e33426eb4d43c248727c1d55"
        }
      ]
    }
  ]
}
