{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mini",
    "module": "mini-data",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "okhxofx7ffagpdgzvki37x2zsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.data",
          "module": "spring-data-relational",
          "version": {
            "requires": "2.0.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-util",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-data-1.0.jar",
          "url": "mini-data-1.0.jar",
          "size": 95443,
          "sha512": "ccbab958b8e28a47efe85016308a77490b38430fef6030e4a0f2988ce536adf1e6a14e98a5bff858a872c807b8c8d25b43f5bf3c4c41eed9ce1f348b4595a548",
          "sha256": "6951c86d565ceb8228ec39256fa58f82698ee151ffb71d67ee0b3a922885a0bf",
          "sha1": "f4a33c4982b0f4f95173841f64922250e2cc1386",
          "md5": "9caea5ed01b4ea3e78833c684d09ef6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-relational",
          "version": {
            "requires": "2.0.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-util",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-data-1.0.jar",
          "url": "mini-data-1.0.jar",
          "size": 95443,
          "sha512": "ccbab958b8e28a47efe85016308a77490b38430fef6030e4a0f2988ce536adf1e6a14e98a5bff858a872c807b8c8d25b43f5bf3c4c41eed9ce1f348b4595a548",
          "sha256": "6951c86d565ceb8228ec39256fa58f82698ee151ffb71d67ee0b3a922885a0bf",
          "sha1": "f4a33c4982b0f4f95173841f64922250e2cc1386",
          "md5": "9caea5ed01b4ea3e78833c684d09ef6f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-data-1.0-javadoc.jar",
          "url": "mini-data-1.0-javadoc.jar",
          "size": 628358,
          "sha512": "a2b92a19bd417736d31261ab3f62f5f6e0935143f1d6d7155c85cfa44eaabc33c6526b12d8f07f981e867819ee5dfa48535cea6a7b6dfa8d08e1677296a2a0e6",
          "sha256": "8b79f56249b356743341a0061c07dfe675aedf3972cf6647ae39bd318a72ad52",
          "sha1": "fe6bd498f6ad98fbc9240cf67e4304fb34faa102",
          "md5": "d808a6b3c6e001706d7971b3f02659a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-data-1.0-sources.jar",
          "url": "mini-data-1.0-sources.jar",
          "size": 31521,
          "sha512": "01a63025f31fe7ab1d2da3d8889c796ae3f4de7bd7460a2449153eeb1e18936d5c250d29dc719b779e60ed9a13fbbf2d2a4d170807b7e1eaaee65acd2d2eb45a",
          "sha256": "f8a6b738443ff5c16876ff835abc7bb48ae048898076f933ee9b135a588b40c4",
          "sha1": "2bdcf6f4f58ca674300a11af8de10bb70d96089a",
          "md5": "78529fd5000c0d21dff6259443d80c22"
        }
      ]
    }
  ]
}
