{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mini",
    "module": "mini-data",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "jsh6lutrozhspp5ias5xw3jbpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.data",
          "module": "spring-data-relational",
          "version": {
            "requires": "2.0.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-util",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-data-1.0.jar",
          "url": "mini-data-1.0.jar",
          "size": 95666,
          "sha512": "103637a0fa9c032dc9f842c6eca34e69490b7315fd156bca40b2648502ad47248a23c50fafbf4e85b3d4a0cc31d26ec28336b64c1d4518d69566565b40d4cf9f",
          "sha256": "ff32b115834b14448a65f49bbec970a330036037b5dccd4fea186dfb98c08cb8",
          "sha1": "ecee26ef142630ef77c63bc317d8c827b8db56c8",
          "md5": "761fd58555468389496ded35d005b783"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-relational",
          "version": {
            "requires": "2.0.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "com.mini",
          "module": "mini-util",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mini-data-1.0.jar",
          "url": "mini-data-1.0.jar",
          "size": 95666,
          "sha512": "103637a0fa9c032dc9f842c6eca34e69490b7315fd156bca40b2648502ad47248a23c50fafbf4e85b3d4a0cc31d26ec28336b64c1d4518d69566565b40d4cf9f",
          "sha256": "ff32b115834b14448a65f49bbec970a330036037b5dccd4fea186dfb98c08cb8",
          "sha1": "ecee26ef142630ef77c63bc317d8c827b8db56c8",
          "md5": "761fd58555468389496ded35d005b783"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-data-1.0-javadoc.jar",
          "url": "mini-data-1.0-javadoc.jar",
          "size": 628994,
          "sha512": "8b890a5233822e6d9b000effbc5dafdd244937a8d3b77507a8159d02e84b7aedb7e6524cc5ac0a214fee0a1416b9d804ab48d9e68720e89a7be4f37f12647f08",
          "sha256": "c413414e768b9531c3776e4bc2d93321bb8db20e8f8a448bee8d137f74319a31",
          "sha1": "7f58da2cced215df8fa1aacae4363f0a7868b849",
          "md5": "deee91510d26fd700dff014a295c6a2f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mini-data-1.0-sources.jar",
          "url": "mini-data-1.0-sources.jar",
          "size": 31588,
          "sha512": "77f0267fe44ee98737ade9a6ae9928a3dc89c5a6833c33abfdb91b9a5ab4af3d805afc1db164aefb1941366a06233d9fbd76e78267519bf06e823a9ecc345b5f",
          "sha256": "6fb7228238f3da517af00fd0ba5619633b75c239d85ef211a9d38f7c27d91ce4",
          "sha1": "26611da64360bc1282fc2a52cfa78a9fe6940b83",
          "md5": "3b801513aabb9eed0ff119edde04f4d4"
        }
      ]
    }
  ]
}
